blogapp/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns=[
    path("",views.home,name="home"),
    path("detail/<str:slug>",views.product_detail,name="product_detail"),
    path("old_url",views.old_url,name="old_func_url"),
    path("new_url_page001",views.new_url,name="new_page_url"),
    path("contact",views.contact,name="contact"),
    path("about",views.about,name="about")
]

blogproject/urls.py
from django.contrib import admin
from django.urls import path,include

handler404='blogproject.views.error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('blogapp.urls'))
]

blogapp/models.py
from django.db import models
from django.utils.text import slugify

#creating of category

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

# Create your models here.
class table1(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    img_url = models.URLField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True,blank=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.title)
        super().save(*args,**kwargs)

    def  __str__(self):
        return self.title
    

class aboutus(models.Model):
    content = models.TextField()

blogapp/forms.py
from django import forms

class contactform(forms.Form):
    name = forms.CharField(label='Name',max_length=100,required=True)
    email = forms.EmailField(label='Email',required=True)
    message = forms.CharField(label='Message',required=True)

blogapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.urls import reverse
from .models import table1,aboutus
import logging
from django.http import Http404
from django.core.paginator import Paginator
from .forms import contactform

# Create your views here.
# static demo data in list
# lis = [
#         {'id':1,'title':'post1','content':'content of post1'},
#         {'id':2,'title':'post2','content':'content of post2'},
#         {'id':3,'title':'post3','content':'content of post3'},
#         {'id':4,'title':'post4','content':'content of post4'},
#         {'id':5,'title':'post5','content':'content of post5'}
#     ]

def home(request):
    blog_value = 'Latest Posts'
    #getting data from post model
    lis = table1.objects.all()

    #paginate
    paginator = Paginator(lis,5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)


    return render(request,'home.html',{'blog_value': blog_value,'page':page_obj})

def product_detail(request,slug):
    #static data
    #post = next((item for item in lis if item['id'] == int(pk)), None)

    #get model data by post id 
    try:
        post = table1.objects.get(slug=slug)
        related_post = table1.objects.filter(category = post.category).exclude(pk = post.id)

    except table1.DoesNotExist:
        raise Http404("post does not exist!")

    # logger = logging.getLogger("TESTING")
    # logger.debug(f'post variable is {post}')
    return render(request,'product_detail.html',{'tit':post,'list_post':related_post})

def old_url(request):
    return redirect(reverse("blog:new_page_url"))

def new_url(request):
    return HttpResponse("this is the new url")

def contact(request):
    if request.method == 'POST':
        form = contactform(request.POST)
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')

        logger=logging.getLogger('testing')
        if form.is_valid():
            logger.debug(f"post data is {form.cleaned_data['name']} {form.cleaned_data['email']} {form.cleaned_data['message']}")
            success_message = "your email has been sent!"
            return render(request,'contact.html',{'form':form, 'success_message':success_message})
        else:
            logger.debug("form validation failure")
        return render(request,'contact.html',{'form':form, 'name':name, 'email':email, 'message':message})
    return render(request,'contact.html')

def about(request):
    about_us = aboutus.objects.first().content
    return render(request,'about.html',{'about_us':about_us})

blogproject/views.py
from django.shortcuts import render

def error(request,exception):
    return render(request,'404.html',status=404)

blogapp/templates/about.html
{% extends 'base.html' %}
{%load static%}

{% block content %}
    <div class="container-fluid ">
        <h3>About Us</h3>
        <div class="d-flex gap-3 justify-content-center mt-5">
            <img src="https://picsum.photos/300/300" alt="">
            <div class="content">
               {{about_us}}
            </div>
            
        </div>
    </div>
{% endblock %}

blogapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{blog_value | default:"Document"}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body >
   <!-- <header content include> -->
    {% include 'includes/header.html' %}

    <!-- <dynamic content> -->

    {% block content %}
    {% endblock %}

   <!-- <footer content include> -->
    {% include 'includes/footer.html' %}

     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

blogapp/templates/contact.html
{% extends 'base.html' %}
{%load static%}

{% block content %}
    <div class="container-fluid ">
        <div class="d-flex justify-content-center mt-5">
            <div class="d-flex gap-3 flex-column">
                <h3>Contact Form</h3>

                {% for field in form %}
                    {% if field.errors %}
                        <div class="col-2">
                            <span class="fw-bold">{{field.label_tag}}</span>
                            {% for error in field.errors %}
                            <span class="text-danger">{{error}}</span>
                            {% endfor %}
                        </div>
                    {% endif %}
                {% endfor %}

                {% if success_message %}
                        <div class="alert-alert-success" role="alert">
                            {{success_message}}
                        </div>
                {% endif %}
                
                <form method="post" class="row g-3">
                    {% csrf_token %}
                    <div class="col-md-6">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="name" value="{{name}}" name="name" required>
                    </div>
                    <div class="col-md-6">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" value="{{email}}"  name="email" required>
                    </div>
                    <div class="col-12">
                        <label for="message" class="form-label">Message</label>
                        <textarea class="form-control" id="message" value="{{message}}" name="message" rows="4" required></textarea>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        
    </div>
{% endblock %}

blogapp/templates/home.html
{% extends 'base.html' %}
{%load static%}

{% block content %}
    <div class="container-fluid ">
        <div class="row">
            <h2 >{{blog_value}}</h2>
        </div>
        <div class="row m-3">

        {% if page %}
            {% for i in page %}    
                <div class="col-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <img style="height:300; width:300;" src="{{i.img_url}}" class="img-fluid" alt="...">
                                </div>
                                <div class="col-md-8">
                                    <h5 class="card-title">{{i.title}}</h5>
                                    <p class="card-text">{{i.content|truncatechars:50}}</p>
                                    <div class="d-flex justify-content-between">
                                        <a href="{% url 'blog:product_detail' slug=i.slug %}">Read More</a>
                                        <a class="text-decoration-none text-dark fw-bold" href="#">{{i.category.name}}</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

            <div class="col-12 my-3">
                {%if page.has_other_pages %}
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {% if page.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1" aria-label="First">
                                <span aria-hidden="true">&laquo; first</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{page.prevoius_page_number}}" aria-label="Previous">
                                <span aria-hidden="true">previous</span>
                            </a>
                        </li>
                        {% endif %}
                        <li class="page-item"><span class="page-link">Page {{page.number}} of {{page.paginator.num_pages}}.</span></li>
                        {% if page.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{page.next_page_number}}" aria-label="Next">
                                <span aria-hidden="true">next</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{page.paginator.num_pages}}" aria-label="Last">
                                <span aria-hidden="true">last &raquo;</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}                
            </div>
        {% else %}
        <p>No Post Available</p>
        {% endif %}
        
            
           
       
        
    </div>
{% endblock %}
   

blogapp/templates/includes/footer.html
  <footer class="bg-dark text-light p-3 fixed-bottom">
      <div class="col-4 d-flex justify-content-center align-items-center">
        <span class="text-light">© 2021 Company, Inc</span>
      </div>
  </footer>

blogapp/templates/includes/header.html
<header class="p-3 bg-dark text-white">
    <div class="row">
        <div class="col">
            <a class="text-light text-decoration-none" href="/"><h3>Blog</h3></a>
        </div>
        <div class="col">
            <div class="d-flex justify-content-center gap-3">
                <a class="text-light text-decoration-none" href="/">Home</a>
                <a class="text-light text-decoration-none" href="{% url 'blog:about' %}">About</a>
                <a class="text-light text-decoration-none" href="{% url 'blog:contact' %}">Contact</a>
            </div>
        </div>
    </div>
</header>

blogapp/templates/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid ">
       
        <div class="row">
            <div class="col-lg-8">
              <h1 class="mb-4">{{tit.title}}<small style="font-size:22px">({{tit.category.name}})</small></h1>
              <p class="text-muted">Posted on {{tit.created_at|date:"F j, Y"}}</p>
              <img src="{{tit.img_url}}" class="img-fluid mb-1" alt="Blog Image">
              <p>{{tit.content}}</p>
            </div>
            <div class="col-lg-4">
              <div class="card mt-3">
                <div class="card-body">
                  <h5 class="card-title">Related Posts</h5>
                  <ul class="list-unstyled">
                    {% for i in list_post%}
                    <li><a href="{% url 'blog:product_detail' slug=i.slug %}">{{i.title}}</a></li>
                    {% endfor%}
                  </ul>
                </div>
              </div>
            </div>
        </div>
    </div>
{% endblock %}
   